services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - CLUSTER_HOSTNAME=weaviate
      - CLUSTER_BROADCAST_ADDR=weaviate
      - CLUSTER_PORT=7000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # - WEAVIATE_PASSWORD=<your_password_here> # Optional password for additional security
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - backend
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  redis_data:
  weaviate_data:

networks:
  backend:
    driver: bridge
